#!/bin/sh

rm -rf ca
rm -f example-root*
rm -f example-int1*

# Root
echo "CREATE ROOT CA"
./ca_create \
	-b ca \
	-n example-root \
	-c US \
	-s "New York" \
	-l Exampleton \
	-o "Example Industries Inc." \
	-u "IT Department" \
	-e certmonger@example.com \
	-v ocsp.example.com

# Intermediate
echo "CREATE INTERMEDIATE CA BELOW ROOT CA"
./ca_create -f example-int1.example.edu \
	-b ca \ 
	-n example-int1 \ 
	-c US \
	-s "New York" \
	-l Exampleton \
	-o "Example Industries Inc." \
	-u "IT Department" \
	-e certmonger@example.com \
	-v ocsp.example.com

# Sign
echo "SIGN INTERMEDIATE CA'S CSR"
./ca_signcsr -i ca/example-root example-int1-cert*.csr

